//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Desctop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Item()
        {
            this.ItemImages = new HashSet<ItemImages>();
            this.UserItems = new HashSet<UserItems>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public bool IsPublished { get; set; }
        public double Price { get; set; }
        public int Count { get; set; }
        public byte[] Image { get; set; }
        public byte[] Doc { get; set; }
        public string DocFormat { get; set; }
        public System.DateTime DateStart { get; set; }
        public System.TimeSpan TimeStart { get; set; }
        public string Description { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ItemImages> ItemImages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserItems> UserItems { get; set; }
    }
}
