//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Desctop.Models
{
    using System;
    using System.Collections.Generic;
    using System.Linq;

    public partial class UserItems
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public int ItemId { get; set; }
    
        public virtual Item Item
        {
            get
            {
                return App.Items.FirstOrDefault(x => x.Id == ItemId);
            }
            set
            {
                ItemId = value.Id;
            }
        }
        public virtual User User
        {
            get
            {
                return App.Users.FirstOrDefault(x => x.Id == UserId);
            }
            set
            {
                UserId = value.Id;
            }
        }
    }
}
